(function(){'use strict';const A=window.JC_APP,$=(id)=>document.getElementById(id);let data=null;
const esc=(v)=>String(v??'').replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));
const money=(v)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});const digits=(v)=>{let p=String(v||'').replace(/\D/g,'');if(p&&p.length<=11)p='55'+p;return p};
function toast(t,bad=false){A.toast(t,bad?'error':'ok')}
function setView(ok){$('loginView').classList.toggle('hidden',ok);$('appView').classList.toggle('hidden',!ok);$('logoutBtn').classList.toggle('hidden',!ok)}
async function load(){const {data:d,error}=await A.client.rpc('get_reseller_dashboard');if(error)throw error;if(!d?.profile||d?.settings?.enabled===false)throw new Error('Sua área de revenda não está liberada ou está bloqueada.');data=d;setView(true);$('topStatus').textContent='Revendedor: '+d.profile.full_name;$('welcome').textContent='Olá, '+d.profile.full_name;render();}
function render(){const sales=data.sales||[],customers=data.customers||[],done=sales.filter(x=>x.status==='created'),pending=sales.filter(x=>!['created','rejected','cancelled'].includes(x.status));$('statCustomers').textContent=customers.length;$('statPending').textContent=pending.length;$('statSales').textContent=money(done.reduce((a,x)=>a+Number(x.customer_price||0),0));$('statPlatform').textContent=money(done.reduce((a,x)=>a+Number(x.platform_fee||0),0));$('statProfit').textContent=money(done.reduce((a,x)=>a+Number(x.reseller_profit||0),0));$('permissionList').innerHTML=(data.functions||[]).map(f=>`<span>${esc(f.name)}</span>`).join('')||'<span>Nenhuma função liberada</span>';renderPlans();renderCustomers();renderSales();renderSettings();}
function resellerPrice(months){const p=(data.plans||[]).find(x=>Number(x.months)===Number(months));const custom=Number(data.settings?.price_table?.[String(months)]);return custom>=Number(p?.value||0)?custom:Number(p?.value||0)}
function renderPlans(){const plans=data.plans||[];$('salePlan').innerHTML=plans.map(p=>`<option value="${p.months}">${esc(p.name)} — mínimo ${money(p.value)}</option>`).join('');$('resellerPriceGrid').innerHTML=plans.map(p=>`<div class="field"><label>${esc(p.name)} — mínimo ${money(p.value)}</label><input data-price-months="${p.months}" type="number" step="0.01" min="${Number(p.value)}" value="${resellerPrice(p.months)}"></div>`).join('');updateSaleType();}
function updateSaleType(){const type=$('saleType').value,isM=type==='monthly',isC=type==='credits',isT=type==='test';$('salePlanField').classList.toggle('hidden',!isM);$('saleCreditsField').classList.toggle('hidden',!isC);$('salePrice').disabled=isT;if(isT)$('salePrice').value='0';else if(isM)$('salePrice').value=resellerPrice($('salePlan').value).toFixed(2);updateCalculation();}
function updateCalculation(){const type=$('saleType').value,price=Number($('salePrice').value||0),percent=Number(data.settings?.fee_percent||30);let base=0;if(type==='monthly'){base=Number((data.plans||[]).find(p=>String(p.months)===$('salePlan').value)?.value||0)}const fee=type==='test'?0:Math.max(base,Math.round(price*percent)/100);const profit=type==='test'?0:price-fee;$('saleCalculation').textContent=type==='test'?'Teste demonstrativo: nenhuma taxa e nenhuma função real.':`Cliente paga ${money(price)} • você paga à plataforma ${money(fee)} • seu saldo estimado ${money(profit)}.`;}
async function submitSale(){const type=$('saleType').value,plan=type==='monthly'?Number($('salePlan').value):0,price=Number($('salePrice').value||0);const body={p_sale_kind:'new',p_client_user_id:null,p_username:$('saleUsername').value.trim(),p_full_name:$('saleFullName').value.trim(),p_email:$('saleEmail').value.trim(),p_whatsapp:$('saleWhatsapp').value,p_whatsapp2:$('saleWhatsapp2').value,p_whatsapp3:$('saleWhatsapp3').value,p_account_type:type,p_plan_months:plan,p_credits_quantity:type==='credits'?Number($('saleCredits').value||0):0,p_customer_price:price,p_notes:$('saleNotes').value||null};const {data:r,error}=await A.client.rpc('reseller_submit_sale',body);if(error)throw error;toast(`Solicitação enviada. Valor devido à plataforma: ${money(r.platform_fee)}.`);['saleUsername','saleFullName','saleEmail','saleWhatsapp','saleWhatsapp2','saleWhatsapp3','saleNotes'].forEach(id=>$(id).value='');await load();}
function billSettings(){return data.settings?.billing_settings||{}}
function chargeMessage(c,day){const s=billSettings(),tpl=day===10?(s.day10_message||'Olá, {nome}! Hoje é o último dia para regularizar seu plano {plano}, no valor de {valor}. Após hoje o acesso poderá ser bloqueado.\n\n{pix_bloco}'):(s.day5_message||'Olá, {nome}! Seu plano {plano}, no valor de {valor}, vence em {vencimento}. O pagamento pode ser realizado até o dia 10.\n\n{pix_bloco}');const pix=['DADOS PARA PAGAMENTO VIA PIX',s.pix_holder&&'Titular: '+s.pix_holder,s.pix_bank&&'Banco: '+s.pix_bank,(s.pix_key_type||s.pix_key)&&`Chave PIX (${s.pix_key_type||'chave'}): ${s.pix_key||''}`].filter(Boolean).join('\n');const vars={nome:c.full_name,plano:c.plan_name||'',valor:money(c.plan_value),vencimento:c.expires_at?new Date(c.expires_at+'T12:00:00').toLocaleDateString('pt-BR'):'',pix_bloco:pix};return tpl.replace(/\{(nome|plano|valor|vencimento|pix_bloco)\}/g,(_,k)=>vars[k]||'').trim()}
function openWhats(c,day){const p=digits(c.whatsapp);if(!p)return toast('WhatsApp inválido.',true);window.open('https://wa.me/'+p+'?text='+encodeURIComponent(chargeMessage(c,day)),'_blank')}
async function renewal(c){const months=Number(c.plan_months||1),price=resellerPrice(months);const {data:r,error}=await A.client.rpc('reseller_submit_sale',{p_sale_kind:'renewal',p_client_user_id:c.id,p_username:c.username,p_full_name:c.full_name,p_email:c.email,p_whatsapp:c.whatsapp,p_whatsapp2:c.whatsapp2,p_whatsapp3:c.whatsapp3,p_account_type:c.account_type==='credits'?'credits':'monthly',p_plan_months:c.account_type==='monthly'?months:0,p_credits_quantity:c.account_type==='credits'?10:0,p_customer_price:price,p_notes:'Renovação solicitada pelo revendedor'});if(error)throw error;toast('Renovação enviada para aprovação. Plataforma: '+money(r.platform_fee));await load();}
function renderCustomers(){$('customerList').innerHTML=(data.customers||[]).length?(data.customers||[]).map(c=>`<div class="item"><div class="item-head"><div><b>${esc(c.full_name)}</b> <span class="badge ${c.status==='active'?'':'bad'}">${esc(c.status)}</span><br><small>@${esc(c.username)} • ${esc(c.whatsapp||'')}<br>${esc(c.plan_name||'')} ${c.expires_at?'• vence '+new Date(c.expires_at+'T12:00:00').toLocaleDateString('pt-BR'):''}</small></div><div class="actions"><button class="btn blue" data-day5="${c.id}">Cobrar dia 5</button><button class="btn amber" data-day10="${c.id}">Cobrar dia 10</button><button class="btn green" data-renew="${c.id}">Solicitar renovação</button></div></div></div>`).join(''):'<div class="muted">Nenhum cliente aprovado ainda.</div>';document.querySelectorAll('[data-day5]').forEach(b=>b.onclick=()=>openWhats(data.customers.find(c=>c.id===b.dataset.day5),5));document.querySelectorAll('[data-day10]').forEach(b=>b.onclick=()=>openWhats(data.customers.find(c=>c.id===b.dataset.day10),10));document.querySelectorAll('[data-renew]').forEach(b=>b.onclick=()=>renew(data.customers.find(c=>c.id===b.dataset.renew)).catch(e=>toast(e.message,true)));}
function renderSales(){$('salesList').innerHTML=(data.sales||[]).length?(data.sales||[]).map(x=>`<div class="item"><div class="item-head"><div><b>${esc(x.full_name)}</b> <span class="badge ${x.status==='created'?'':'warn'}">${esc(x.status)}</span><br><small>${x.account_type==='monthly'?x.plan_months+' mês(es)':x.account_type==='credits'?x.credits_quantity+' créditos':'Teste'} • ${new Date(x.created_at).toLocaleString('pt-BR')}</small></div><div><b>${money(x.customer_price)}</b><br><small>Plataforma ${money(x.platform_fee)} • seu saldo ${money(x.reseller_profit)}</small></div></div></div>`).join(''):'<div class="muted">Nenhuma venda enviada.</div>';}
function renderSettings(){const s=billSettings();$('pixHolder').value=s.pix_holder||'';$('pixBank').value=s.pix_bank||'';$('pixType').value=s.pix_key_type||'Aleatória';$('pixKey').value=s.pix_key||'';$('msgDay5').value=s.day5_message||'Olá, {nome}! Seu plano {plano}, no valor de {valor}, vence em {vencimento}. O pagamento pode ser realizado até o dia 10.\n\n{pix_bloco}';$('msgDay10').value=s.day10_message||'Olá, {nome}! Hoje é o último dia para regularizar seu plano {plano}, no valor de {valor}. Após hoje o acesso poderá ser bloqueado.\n\n{pix_bloco}';}
async function saveSettings(){const price={};document.querySelectorAll('[data-price-months]').forEach(i=>price[i.dataset.priceMonths]=Number(i.value||0));const billing={pix_holder:$('pixHolder').value.trim(),pix_bank:$('pixBank').value.trim(),pix_key_type:$('pixType').value,pix_key:$('pixKey').value.trim(),day5_message:$('msgDay5').value.trim(),day10_message:$('msgDay10').value.trim()};const {error}=await A.client.rpc('reseller_save_settings',{p_price_table:price,p_billing_settings:billing});if(error)throw error;toast('Configurações da revenda salvas.');await load();}
$('loginForm').onsubmit=async(e)=>{e.preventDefault();$('loginMsg').textContent='Entrando...';try{await A.login($('loginUser').value,$('loginPass').value);await load();}catch(err){$('loginMsg').textContent=err.message||'Não foi possível entrar.'}};$('logoutBtn').onclick=async()=>{await A.client.auth.signOut();location.reload()};document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.pane).classList.add('active')});$('saleType').onchange=updateSaleType;$('salePlan').onchange=updateSaleType;$('salePrice').oninput=updateCalculation;$('submitSaleBtn').onclick=()=>submitSale().catch(e=>toast(e.message,true));$('saveSettingsBtn').onclick=()=>saveSettings().catch(e=>toast(e.message,true));
(async()=>{if(!A.ready)return;const {data:{session}}=await A.client.auth.getSession();if(session)load().catch(async e=>{await A.client.auth.signOut();setView(false);$('loginMsg').textContent=e.message})})();})();
